baseURL = 'https://migueldavid.eu/'
languageCode = 'en-us'
title = 'migueldavid.eu'
theme = 'hygge'

[params]
  name = "migueldavid.eu"
  bio = "Engineering Manager building reliable systems and high-performing teams"
  aboutBio = "I build reliable systems and grow engineering teams. I've done this from Porto to London to Brussels, 7 countries total, usually while figuring out a new language and where to get decent tea. I live in Brussels now with my wife, two small humans, and a dog named after the real hero of Middle-earth."
  location = "Brussels, Belgium"
  blogURL = "https://migueldavid.eu"  # External blog URL

  [params.social]
    twitter = "https://x.com/migueldavidx"
    bluesky = "https://bsky.app/profile/migueldavid.eu"
    github = "https://github.com/minac"
    linkedin = "https://linkedin.com/in/migueldavid"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "https://migueldavid.eu/blog"
    weight = 1
